# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('bid', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(blank=True, verbose_name='\u5185\u5bb9')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u8bc4\u8bba')),
                ('clicks', models.IntegerField(verbose_name='\u70b9\u51fb\u91cf')),
                ('time', models.TimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Description', verbose_name='\u5206\u7c7b'),
        ),
    ]
