# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bid',
            new_name='id',
        ),
    ]
