# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170317_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u63d0\u4ea4\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf'),
        ),
    ]
