# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170317_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='text',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.ManyToManyField(to='blog.Description', verbose_name='\u5206\u7c7b'),
        ),
    ]
