# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:17
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170317_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, default='\u5728\u6b64\u8f93\u5165', verbose_name='\u5185\u5bb9'),
        ),
    ]
